### ISSUE TITLE
re-frame.core/dispatch-sync

### ISSUE THREAD

**Issue by awb99** [babashka/sci.configs#25]
I am using re-frame inside sci and I add the ns-bindings via sci.configs.
I noticed that re-frame.core/dispatch-sync is not available in the namespace.
This is really weird, since re-frame.core/dispatch *is* available.
Could it be that the copy-ns implementation has a problem when the function-name 
contains a "-" inside? Or perhaps "sync" is somehow reserved/special and therefore
does not get included?

What is weirder is that inside my app I sometimes used dispatch-sync; so it is inside
the bundle. Just the sci namespace does not have it.

I will investigate more into this myself, as I guess it more likely is an error inside my app.

Regards

**Comment by borkdude** [comment]
The tests include a reference to dispatch-sync as you can see here:
https://github.com/babashka/sci.configs/blob/main/test/re_frame/re_frame_test.cljs
and they run successfully on CI.

**Comment by awb99** [comment]
My mistake!  Just found out that my old non-sci-configs config was overriding this namespace.
Sorry.

**Comment by awb99** [comment]
many thanks!

**Comment by awb99** [comment]
closed.
